ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_type VARCHAR(20) NOT NULL DEFAULT 'one_time';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS recurring_cadence VARCHAR(20);

ALTER TABLE deals ADD COLUMN IF NOT EXISTS retainer_skipped BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS retainer_invoice_id UUID REFERENCES invoices(id) ON DELETE SET NULL;
